Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/jammy64"
    config.vm.box_check_update = true

    # =========================
    # Server
    # =========================

    config.vm.define "bberkrouS" do |server|

        server.vm.hostname = "bberkrouS"
        server.vm.network "private_network", ip: "192.168.56.110"

        server.vm.provider "virtualbox" do |vb|
            vb.gui = false
            vb.memory = "3072"
            vb.cpus = 2
        end

        server.vm.provision "shell",
            path: "scripts/ssh/ssh_install.sh"

        server.vm.provision "file",
            source: File.expand_path("~/.ssh/id_ed25519.pub"),
            destination: "/tmp/id_ed25519.pub"

        server.vm.provision "shell",
            path: "scripts/ssh/ssh_access.sh"

        server.vm.provision "shell",
            path: "scripts/k3s/k3s_controller_install.sh"

        server.vm.provision "shell",
            path: "scripts/helm/helm_install.sh"
    end

    # =========================
    # GitLab | Server worker
    # =========================

    config.vm.define "gitlab" do |gitlab|
        gitlab.vm.hostname = "gitlab"
        gitlab.vm.network "private_network", ip: "192.168.56.111"

        gitlab.vm.provider "virtualbox" do |vb|
            vb.gui = false
            vb.memory = "8192"
            vb.cpus = 6
        end

        gitlab.vm.provision "shell",
            path: "scripts/ssh/ssh_install.sh"

        gitlab.vm.provision "file",
            source: File.expand_path("~/.ssh/id_ed25519.pub"),
            destination: "/tmp/id_ed25519.pub"

        gitlab.vm.provision "shell",
            path: "scripts/ssh/ssh_access.sh"

        gitlab.vm.provision "shell",
            path: "scripts/k3s/k3s_agent_install.sh",
            env: {
                "NODE_IP" => "192.168.56.111",
                "NODE_ROLE" => "gitlab",
                "NODE_LABEL" => "gitlab"
            }

        # gitlab.vm.provision "shell", 
        # path: "scripts/gitlab/gitlab_install.sh"
    end

    # =========================
    # DATA | Server Worker
    # =========================

    config.vm.define "data" do |data|
        data.vm.hostname = "data"
        data.vm.network "private_network", ip: "192.168.56.112"

        data.vm.provider "virtualbox" do |vb|
            vb.gui = false
            vb.memory = "8192"
            vb.cpus = 6
        end

        data.vm.provision "shell",
            path: "scripts/ssh/ssh_install.sh"

        data.vm.provision "file",
            source: File.expand_path("~/.ssh/id_ed25519.pub"),
            destination: "/tmp/id_ed25519.pub"

        data.vm.provision "shell",
            path: "scripts/ssh/ssh_access.sh"

        data.vm.provision "shell",
            path: "scripts/k3s/k3s_agent_install.sh",
            env: {
                "NODE_IP" => "192.168.56.112",
                "NODE_ROLE" => "data",
                "NODE_LABEL" => "data"
            }

        # data.vm.provision "shell", 
        # path: "scripts/gitlab/data_install.sh"
    end
    

    # =========================
    # CD | Server Worker
    # =========================

    config.vm.define "cd" do |cd|
        cd.vm.hostname = "cd"
        cd.vm.network "private_network", ip: "192.168.56.113"

        cd.vm.provider "virtualbox" do |vb|
            vb.gui = false
            vb.memory = "3072"
            vb.cpus = 2
        end
        
        cd.vm.provision "shell",
            path: "scripts/ssh/ssh_install.sh"

        cd.vm.provision "file",
            source: File.expand_path("~/.ssh/id_ed25519.pub"),
            destination: "/tmp/id_ed25519.pub"

        cd.vm.provision "shell",
            path: "scripts/ssh/ssh_access.sh"

        cd.vm.provision "shell",
            path: "scripts/k3s/k3s_agent_install.sh",
            env: {
                "NODE_IP" => "192.168.56.113",
                "NODE_ROLE" => "cd",
                "NODE_LABEL" => "cd"
            }

        # cd.vm.provision "shell", 
        # path: "scripts/gitlab/cd_install.sh"
    end


    # =========================
    # Post cluster bootstrap
    # =========================

    config.trigger.after :up, type: :command do |trigger|
        trigger.name = "Post cluster bootstrap"
        trigger.info = "Installing Kubernetes services after cluster startup"

        trigger.run = {
            path: File.expand_path(
                "scripts/bootstrap/post_up.sh",
                __dir__
            )
        }
    end

end