LOGIN     = "cpeterea"
SERVER    = "#{LOGIN}S"
SERVER_IP = "192.168.56.110"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.define SERVER do |server|
    server.vm.hostname = SERVER
    server.vm.network "private_network", ip: SERVER_IP
    server.vm.provider "virtualbox" do |vb|
      vb.name   = SERVER
      vb.cpus   = 1
      vb.memory = 1024
    end
    server.vm.provision "shell", path: "scripts/k3s/k3s_server_install.sh"
  end
end