Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"
  config.vm.box_check_update = true

  # =========================
  # Server
  # =========================
  config.vm.define "bberkrouS" do |server|

    server.vm.hostname = "bberkrouS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "3072"
      vb.cpus = 2
    end

    server.vm.provision "shell",
      path: "scripts/ssh/ssh_install.sh"

    server.vm.provision "file",
      source: File.expand_path("~/.ssh/id_ed25519.pub"),
      destination: "/tmp/id_ed25519.pub"

    server.vm.provision "shell",
      path: "scripts/ssh/ssh_access.sh"

    server.vm.provision "shell",
      path: "scripts/k3s/k3s_controller_install.sh"
  end


  # =========================
  # Server Worker
  # =========================
  config.vm.define "bberkrouSW" do |worker|

    worker.vm.hostname = "bberkrouSW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "2048"
      vb.cpus = 2
    end

    worker.vm.provision "shell",
      path: "scripts/ssh/ssh_install.sh"

    worker.vm.provision "file",
      source: File.expand_path("~/.ssh/id_ed25519.pub"),
      destination: "/tmp/id_ed25519.pub"

    worker.vm.provision "shell",
      path: "scripts/ssh/ssh_access.sh"

    worker.vm.provision "shell",
      path: "scripts/k3s/k3s_agent_install.sh"
  end

end