LOGIN  = "cpeterea"          # TODO: remplace par ton login 42
SERVER = "#{LOGIN}S"
WORKER = "#{LOGIN}SW"

SERVER_IP = "192.168.56.110"
WORKER_IP = "192.168.56.111"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # Dossier d'échange pour transmettre le node-token au worker (hors repo)
  config.vm.synced_folder "./shared", "/shared", create: true

  config.vm.provider "virtualbox" do |vb|
    vb.cpus   = 1
    vb.memory = 1024
  end

  # ---------- Server (controller) ----------
  config.vm.define SERVER do |server|
    server.vm.hostname = SERVER
    server.vm.network "private_network", ip: SERVER_IP
    server.vm.provider "virtualbox" do |vb|
      vb.name = SERVER
    end
    server.vm.provision "shell", path: "scripts/k3s/k3s_controller_install.sh"
  end

  # ---------- Worker (agent) ----------
  config.vm.define WORKER do |worker|
    worker.vm.hostname = WORKER
    worker.vm.network "private_network", ip: WORKER_IP
    worker.vm.provider "virtualbox" do |vb|
      vb.name = WORKER
    end
    worker.vm.provision "shell", path: "scripts/k3s/k3s_agent_install.sh"
  end
end