apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: gitlab-postgresql
  namespace: gitlab

spec:
  instances: 1

  imageName: ghcr.io/cloudnative-pg/postgresql:17.11-standard-trixie

  postgresql:
    parameters:
      max_locks_per_transaction: "4096"

  affinity:
    nodeSelector:
      workload: data

  bootstrap:
    initdb:
      database: gitlabhq_production
      owner: gitlab
      secret:
        name: gitlab-postgresql-auth

      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS pg_trgm;
        - CREATE EXTENSION IF NOT EXISTS btree_gist;
        - CREATE EXTENSION IF NOT EXISTS amcheck;

  storage:
    storageClass: local-path
    size: 8Gi

  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 2Gi
      cpu: "2"