apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: dev-app

  template:
    metadata:
      labels:
        app: dev-app

    spec:
      containers:
        - name: dev-app
          image: paulbouwer/hello-kubernetes:1.10
          ports:
            - containerPort: 8888
          env:
            - name: MESSAGE
              value: "Hello from dev2"